eProsima/Fast-DDS-monitor

- CMakeLists.txt
> Removed qDebug traces if not in Debug

- qml/ChartsLayout.qml
> Recalculate charts layout width when a chartbox is removed

- include/fastdds-monitor/backend/SyncBackendConnection.h
- include/fastdds-monitor/model/EntityContainerModelItem.h
- include/fastdds-monitor/model/ListItem.h
- include/fastdds-monitor/model/SubListedListItem.h
- include/fastdds-monitor/model/dds/EndpointModelItem.h
- include/fastdds-monitor/model/dds/ParticipantModelItem.h
- include/fastdds-monitor/model/logical/TopicModelItem.h
- include/fastdds-monitor/model/physical/ProcessModelItem.h
- mock/complex_mock/StatisticsBackend.cpp
- mock/static_mock/StatisticsBackend.cpp
- qml/EntityList.qml
- src/Engine.cpp
- src/backend/SyncBackendConnection.cpp
- src/model/ListItem.cpp
- src/model/dds/EndpointModelItem.cpp
- src/model/dds/ParticipantModelItem.cpp
- src/model/logical/TopicModelItem.cpp
- src/model/physical/ProcessModelItem.cpp
Eliminate couts from mock execution.
Refactor Item to store entity kind.
Refactor SyncBackend and Items so every Backedn call is made from SyncBackend.
Eliminate fallthrough.
> Mock clean and Item refactor

- .github/workflows/test.yml
> Activate coverage

- fastdds_monitor.repos
> Fixed fastdds_monitor.repos

- include/fastdds-monitor/backend/SyncBackendConnection.h
- mock/complex_mock/StatisticsBackend.cpp
- mock/static_mock/StatisticsBackend.cpp
- src/Engine.cpp
- src/backend/SyncBackendConnection.cpp
This PR requires to https://github.com/eProsima/Fast-DDS-statistics-backend/pull/49 to be merged beforehand.
> Get_data refactor

- CMakeLists.txt
> Enable run executable double clicking

- qml/DisplayStatisticsDialog.qml
- src/backend/SyncBackendConnection.cpp
> Avoid setting empty entity ids

- CMakeLists.txt
> Build type to Release by default

- include/fastdds-monitor/backend/backend_utils.h
- include/fastdds-monitor/model/model_types.h
- qml/DisplayStatisticsDialog.qml
- src/Engine.cpp
- src/backend/Listener.cpp
- src/backend/SyncBackendConnection.cpp
- src/backend/backend_utils.cpp
- src/model/ListItem.cpp
- test/unittest/utils/backend_utilsTest.cpp
> EntityId all refactor

- controls/ItemDelegate.qml
- fastdds_monitor.pro
- qml.qrc
- qml/ChartsLayout.qml
This PR implements the following feature:
* Custom style for `ComboBox` and `ItemDelegate`
* When dragging and moving `ChartBoxes`, make it possible for the user to move them out of the main panel.
> Fit chartbox to main panel 

- include/fastdds-monitor/backend/backend_utils.h
- src/backend/SyncBackendConnection.cpp
- src/backend/backend_utils.cpp
This implementation of the summary is easy to implement and it is useful when we want the user to customize the summary.
> Summary information

- qml/Panels.qml
> Fixed splitview content overlapping

- .github/actions/install-apt-packages/action.yml
> Update apt in actions

- docs/rst/user_manual/chart_panel.rst
- docs/rst/user_manual/layout.rst
- docs/rst/user_manual/right_panel.rst
- docs/rst/user_manual/select_entity.rst
> Add suggestions modifications to user manual

- mock/CMakeLists.txt
- mock/complex_mock/CMakeLists.txt
- mock/static_mock/CMakeLists.txt
> Downgrade cmake version

- docs/rst/user_manual/chart_panel.rst
- include/fastdds_monitor/Engine.h
- src/Engine.cpp
> Defaul time refactor

- docs/rst/user_manual/chart_panel.rst
- include/fastdds_monitor/Controller.h
- include/fastdds_monitor/Engine.h
- qml/SummaryView.qml
- src/Controller.cpp
- src/Engine.cpp
- src/backend/SyncBackendConnection.cpp
Change no value per NaN in Summary.
New thread to refresh summary.
> Summary refactor

- mock/complex_mock/StatisticsBackend.cpp
- mock/static_mock/StatisticsBackend.cpp
> Fix backend API break in mock

- qml/SummaryView.qml
- src/Engine.cpp
> Fix last entity clicked in dds kind

- qml/DisplayStatisticsDialog.qml
- qml/LogicalView.qml
> Marked new domain as last entity clicked

- qml/LogicalView.qml
> Removed highlight domain at creation

- include/fastdds_monitor/Engine.h
- include/fastdds_monitor/backend/SyncBackendConnection.h
- src/Engine.cpp
- src/backend/SyncBackendConnection.cpp
> Catch exception in init_monitor call

- qml/LogicalView.qml
> Mark new domain as checked

- src/Engine.cpp
> Handle empty vectors

- src/Engine.cpp
> Callback model always update in main thread

- qml/DisplayStatisticsDialog.qml
- src/backend/backend_utils.cpp
> Get correct entity id

- qml/DisplayStatisticsDialog.qml
> Fixed target id on statistics data dialog

- qml.qrc
- qml/DataKindDialog.qml
- qml/DisplayStatisticsDialog.qml
- qml/InfoToolTip.qml
> Added tooltip for labels

- docs/rst/getting_started/tutorial.rst
- include/fastdds_monitor/Controller.h
- include/fastdds_monitor/Engine.h
- include/fastdds_monitor/backend/SyncBackendConnection.h
- include/fastdds_monitor/backend/backend_utils.h
- mock/complex_mock/StatisticsBackend.cpp
- mock/complex_mock/database/Database.cpp
- mock/complex_mock/database/Database.hpp
- mock/complex_mock/entities/headers/Entity.hpp
- mock/complex_mock/entities/source/Entity.cpp
- mock/static_mock/StatisticsBackend.cpp
- qml.qrc
- qml/ChangeAliasDialog.qml
- qml/DifferClickMouseArea.qml
- qml/EntityList.qml
- qml/LeftPanel.qml
- qml/LogicalView.qml
- qml/PhysicalView.qml
- src/Controller.cpp
- src/Engine.cpp
- src/backend/SyncBackendConnection.cpp
- src/backend/backend_utils.cpp
- src/model/ListItem.cpp
- test/unittest/utils/backend_utilsTest.cpp
fastdds_statistics_backend has already merged https://github.com/eProsima/Fast-DDS-statistics-backend/pull/93 so this PR could be tested and included.
> Set entity alias [11878]

- .github/workflows/clang_colcon.meta
- .github/workflows/colcon.meta
- .github/workflows/test.yml
- .github/workflows/test_colcon.meta
- include/fastdds_monitor/backend/Callback.h
- mock/complex_mock/StatisticsBackend.cpp
- src/Engine.cpp
- src/backend/Listener.cpp
- src/backend/SyncBackendConnection.cpp
> Listener callback for update entity info [11879]

- CMakeLists.txt
Signed-off-by: Raul Sánchez-Mateos <raul@eprosima.com>
> Avoid command prompt when application starts

- qml.qrc
- qml/DifferClickMouseArea.qml
- qml/EntitiesMenu.qml
- qml/EntityList.qml
- qml/LeftPanel.qml
- qml/LogicalView.qml
- qml/PhysicalView.qml
> Added menu for all entities

- qml/ChartsLayout.qml
> Increase cache buffer in GridView

- include/fastdds_monitor/statistics/DynamicChartBox.h
- qml/DynamicStatisticsChartView.qml
- src/Engine.cpp
- src/statistics/DynamicChartBox.cpp
> Increase Y axis in historics so all the data is visible

- qml/CustomLegend.qml
- qml/DynamicStatisticsChartView.qml
- qml/HistoricStatisticsChartView.qml
- qml/StatisticsChartBox.qml
This PR implements:
- Increase re-name legend text field
- Animate series
- Rename charboxes
> Some minor changes in view

- include/fastdds_monitor/backend/SyncBackendConnection.h
- src/backend/SyncBackendConnection.cpp
> Change magnitude for some dataKinds

- qml/ChartsLayout.qml
- qml/CustomLegend.qml
- qml/HistoricStatisticsChartView.qml
- qml/MonitorMenuBar.qml
- qml/MonitorToolBar.qml
- qml/StatisticsChartView.qml
This PR implements:
- Defaut layout to two in a row
- Scroll sidebar always visible in charbox layout
- Change cursor when passing through a chartview
- Change cursor when passing through the legend
- Add missing remove series function in historical chartview
> Add some style features

- qml/ChangeAliasDialog.qml
- qml/CustomLegend.qml
- qml/StatisticsChartBox.qml
> Change names on enter pressed

- include/fastdds_monitor/backend/SyncBackendConnection.h
- src/Engine.cpp
- src/backend/SyncBackendConnection.cpp
Sort results by timestamp.
`count` values to NaN chnge to `0`.
Throughput measured in `B/s`
> Filter and Sort data from backend

- qml.qrc
- qml/CustomLegend.qml
- qml/CustomScrollBar.qml
- qml/EntityList.qml
- qml/LogicalView.qml
- qml/PhysicalView.qml
- qml/StatisticsChartBox.qml
> Style for scrollbar and CustomLegend [12022]

- docs/rst/notes/notes.rst
- docs/rst/notes/previous_versions/v0.1.0.rst
- docs/rst/spelling_wordlist.txt
> v0.2.0 release notes

- CMakeLists.txt
- fastdds_monitor.repos
> Bump to v0.2.0

- CMakeLists.txt
- docs/CMakeLists.txt
- docs/rst/notes/notes.rst
- docs/rst/notes/previous_versions/v0.2.0.rst
- fastdds_monitor.repos
> Bump to 1.0.0

- qml/EntityList.qml
- qml/LogicalView.qml
- qml/PhysicalView.qml
> Fix menu alias break

- docs/rst/developer_manual/installation/sources/linux.rst
- docs/rst/getting_started/entities.rst
Fix typos and add details for installation from sources in Linux.
> Fix typos in documentation [12519]

- src/backend/SyncBackendConnection.cpp
> Fix discovery time data kind name [13019]

- .github/actions/install-openssl-windows/action.yml
> Fix windows github action

- include/fastdds_monitor/statistics/DataChartBox.h
- src/statistics/DataChartBox.cpp
Signed-off-by: Juan López Fernández <juanlopez@eprosima.com>
> Fixed yaxis issue with count measurements

- src/backend/SyncBackendConnection.cpp
Signed-off-by: Raul Sánchez-Mateos <raul@eprosima.com>
> Render mu as u in windows

- docs/rst/notes/notes.rst
- docs/rst/notes/previous_versions/v1.0.0.rst
> Release Notes for v1.1.0

- CMakeLists.txt
> Bump to version v1.1.0

- CMakeLists.txt
- resources/fastdds_monitor.rc
Signed-off-by: Raul Sánchez-Mateos <raul@eprosima.com>
> Add app icon for windows

- fastdds_monitor.repos
> Set dependencies version in repos file

- .github/workflows/test.yml
> Remove GoogleTest release installation for debug CI

- test/unittest/utils/utilsTest.cpp
> Change compare values to unsigned to avoid warning in gtest new versions

- README.md
- docs/rst/formalia/titlepage.rst
- docs/rst/getting_started/entities.rst
- docs/rst/getting_started/monitor.rst
- docs/rst/getting_started/tutorial.rst
- docs/rst/spelling_wordlist.txt
Signed-off-by: Juan López Fernández <juanlopez@eprosima.com>
> Add note with Fast-DDS requirements for statistics

- docs/rst/formalia/titlepage.rst
> Add a warning referencing the history depth

- CMakeLists.txt
- docs/CMakeLists.txt
- docs/rst/notes/notes.rst
- docs/rst/notes/previous_versions/v1.2.0.rst
- package.xml
> Bump to Fast DDS Monitor v1.2.1

- CMakeLists.txt
- docs/rst/notes/notes.rst
- docs/rst/notes/previous_versions/v1.2.1.rst
- package.xml
> Update release notes and bump version [16551]

- include/fastdds_monitor/Controller.h
- include/fastdds_monitor/statistics/StatisticsData.h
- qml/StatisticsChartView.qml
- src/Controller.cpp
- src/statistics/StatisticsData.cpp
Signed-off-by: Irene Bandera <irenebandera@eprosima.com>
> Fix: TypeError: Cannot call methods of null

- qml/ChartsLayout.qml
Fix:
- qrc:/qml/ChartsLayout.qml:168:21: Unable to assign [undefined] to int
> Some bugs found during release testing

- CMakeLists.txt
- docs/CMakeLists.txt
- docs/rst/notes/notes.rst
- docs/rst/notes/previous_versions/v1.5.0.rst
- package.xml
- src/Engine.cpp
This PR should be merged (and rebased) after:
- #196
> Bump to v2.0.0 and include release notes

- CMakeLists.txt
- docs/CMakeLists.txt
- docs/rst/notes/notes.rst
- docs/rst/notes/previous_versions/v2.1.0.rst
- package.xml
- src/Engine.cpp
This PR bumps the Monitor version to v3.0.0, and includes the release notes.
> [21630] Bump version to v3.0.0 and update release notes

- qml/TabLayout.qml
Update TextEdit properties to use eProsima colors
> Change text selection color in idl view

- qml/DomainGraphLayout.qml
- qml/GraphConnection.qml
- Fix connection arrows overlap with topics
-  Fix horizontal bar visualization
> [22842] Fix graphical errors in DomainGraphLayout
